# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('add_appointment', 'Can add appointments')], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
    ]
