# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170802_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('schedule_appointment', 'Can schedule appointments'), ('write_prescription', 'Can write prescriptions')], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
    ]
